"""" Basic Behaviour
set number " display line numbers
set cursorline "highlight currentline
set wrap   " wrap lines
set encoding=utf-8 " set encoding to utf-8
set mouse=a " enable mouse support
set wildmenu " visual autocomplete for command menu
set showmatch " highlight matching parenthesis
set visualbell " blink cursor on error, instead of beeping

"""" Key Bindings

" move vertically by visual line( wrapped lines not skipped)
nmap j gj
nmap k gk

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-H> <C-W><C-H>
nnoremap <C-L> <C-W><C-L>

nmap <C-P> :FZF<CR>

"""" Appearance

"choose colorscheme
colorscheme murphy " options - slate, molokai, badwolf, solarized

" use filetype-based syntax highlighting
syntax enable
filetype plugin indent on

"""" Tab Settings

set tabstop=2 " width of <TAB>
set expandtab " convert tabs to spaces
set shiftwidth=2 " no of spaces to use for auto-indent
set softtabstop=2 "backspace after <TAB> will remove this no of spaces

set autoindent " copy indent from current line when starting a new line
set smartindent " better autoindent add indent after braces

"""" Search Settings

set incsearch " search as characters are entered
set hlsearch " highlight matches

"""" Rust
let g:rustfmt_autosave = 1
let g:rustfmt_emit_files = 1
let g:rustfmt_fail_silently = 0

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<TAB>" :
                  \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
    let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~# '\s'
endfunction

if has('nvim')
    inoremap <silent><expr> <c-space> coc#refresh()
else
    inoremap <silent><expr> <c-@> coc#refresh()
endif

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

"""" Plugins

call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf' " fzf file search
Plug 'junegunn/fzf.vim' " default vim configuration for fzf
Plug 'neoclide/coc.nvim' " intellisense for vim
Plug 'airblade/vim-gitgutter' " show uncommited changes
Plug 'jremmen/vim-ripgrep' " search all files for text
Plug 'dense-analysis/ale'
Plug 'christoomey/vim-tmux-navigator'
Plug 'rust-lang/rust.vim'
Plug 'dense-analysis/ale'

let g:rg_command = 'rg --vimgrep -S'

call plug#end()

" Use rg with ctrlp-plugin

"if executable('rg')
"    let g:ctrlp_user_command = 'rg %s --files --hidden --color=never --glob ""'
"endif
